=== dineshgith/XML_IMCS/src/main/resources/customerXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://com.dinesh/customerXMLSchema"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://com.dinesh/customerXMLSchema">

	<complexType name="Customer">
		<sequence>
			<element name="customerId" type="int"></element>
			<element name="customerName" type="string"></element>
			<element name="annualSalary" type="float"></element>
			<element name="dateOfBirth" type="string"></element>
			<element name="address" type="tns:Address"></element>
			<element name="payment" type="tns:PaymentMethod"></element>
		</sequence>
	</complexType>


	<complexType name="PaymentMethod">
		<sequence>
			<element name="cardNo" type="int"></element>
			<element name="cardName" type="string"></element>
			<element name="dateFrom" type="string"></element>
			<element name="dateTo" type="string"></element>
			<element name="cardType" maxOccurs="unbounded"
				minOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="CREDIT CARD"></enumeration>
						<enumeration value="DEBIT CARD"></enumeration>
					</restriction>
				</simpleType>
			</element>
		</sequence>
	</complexType>


	<complexType name="Address">
		<sequence>
			<element name="houseNo" type="int"></element>
			<element name="street" type="string"></element>
			<element name="city" type="string"></element>
			<element name="state" type="string"></element>
			<element name="zipCode" type="int"></element>
		</sequence>
	</complexType>




    <element name="customer" type="tns:Customer"></element>
</schema>

=== dineshgith/XML_IMCS/target/classes/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:customer xmlns:tns="http://com.dinesh/customerXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://com.dinesh/customerXMLSchema customerXMLSchema.xsd ">
  <tns:customerId>0</tns:customerId>
  <tns:customerName>tns:customerName</tns:customerName>
  <tns:annualSalary>0.0</tns:annualSalary>
  <tns:dateOfBirth>tns:dateOfBirth</tns:dateOfBirth>
  <tns:address>
    <tns:houseNo>0</tns:houseNo>
    <tns:street>tns:street</tns:street>
    <tns:city>tns:city</tns:city>
    <tns:state>tns:state</tns:state>
    <tns:zipCode>0</tns:zipCode>
  </tns:address>
  <tns:payment>
    <tns:cardNo>0</tns:cardNo>
    <tns:cardName>tns:cardName</tns:cardName>
    <tns:dateFrom>tns:dateFrom</tns:dateFrom>
    <tns:dateTo>tns:dateTo</tns:dateTo>
    <tns:cardType>CREDIT CARD</tns:cardType>
  </tns:payment>
</tns:customer>
